config/routes.rb
Rails.application.routes.draw do

  root to: "tests#index"

  resources :tests do
    resources :questions
  end



end

app/models/answer.rb
class Answer < ApplicationRecord

  belongs_to :question
  scope :correct, -> { where(correct: true) }

  #validates :count_replies, on: :create

  private

  def count_replies
    errors.add(:question, 'Too many replies') if question.answers.count > 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  scope :sort_asc, -> { order(title: :asc) }
end

app/models/quesiton.rb
class Question < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers

  validates :title, presence: true
  validates :body, presence: true
  validates :answers, length: { maximum: 4 }
end

app/models/test.rb
class Test < ApplicationRecord

  belongs_to :category
  has_many :questions
  has_and_belongs_to_many :users, join_table: "tests_of_users"
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  scope :level, -> (level) { where(level: level) }

  scope :slow, -> { level(0..1) }
  scope :medium, -> { level(2..3) }
  scope :hard, -> { level(5..Float::INFINITY) }

  scope :name_of_tests, -> ( category_title ) { joins(:categories).where("categories.title LIKE ?", "%#{ category_title }%") }

  validates :title, presence: true, uniqueness: { scope: :level, message: "Title and level must be unique"}
  validates :level, presence: true, numericality: { only_integer: true }
end

app/models/tests_of_user.rb
class TestsOfUser < ApplicationRecord
  belongs_to :test
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_and_belongs_to_many :tests, join_table: "tests_of_users"
  has_many :author_tests, class_name: "Test"

  scope :tests, -> ( level ) { joins(:tests_of_users).where('level=?', level) }

  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, format: { with: /[A-Za-z0-9]+/ }
  validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :get_test
  before_action :get_question, only: [:edit, :update, :show]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_from_test_not_found

  def index
    @questions = @test.questions.all
  end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to test_questions_url(@test)
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to test_questions_url(@test)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to test_questions_url(@test)
  end

  private

  def get_test
    @test = Test.find(params[:test_id])
  end

  def get_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, :published)
  end

  def rescue_from_question_not_found
    render plain: 'Question not found', status: 404
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  before_action :find_test, only: [:show, :edit, :update, :destroy]
  before_action :test_params, only: [:create, :update]

  def index
    @tests = Test.all
  end

  def edit; end

  def show; end

  def new
    @test = Test.new
  end

  def create
    @test = Test.new(test_params)
    @test.user_id = 1
    if @test.save
      redirect_to tests_path
    else
      render :new
    end
  end



  def destroy
    @test.destroy
    redirect_to tests_path
  end

  def update
    if @test.update(test_params)
      redirect_to tests_path
    else
      render :edit
    end
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end

  def test_params
    params.require(:test).permit(:title, :level, :category_id, :published)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_year
    Time.current.year
  end

  def git_repo(author, repo)
    link_to author, repo, target: '_blank'
  end
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create #{question.title} Question"
    else
      "Edit #{question.title} Question"
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper

  TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

  def test_published(test)
    test.published? ? 'Да' : 'Нет'
  end

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end
end

app/views/elements/_footer.html.erb
<footer style="margin-top: 200px;">
  Учебный проект в онлайн-школе <%= link_to 'Thinknetica', 'http://thinknetika.com', target: '_blank' %>. Kahasanov Albert &copy;<%= current_year %>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= render 'elements/footer' %>
  </body>
</html>

app/views/questions/_question.html.erb
<tr>
  <td><%= link_to question.title, edit_test_question_path(@test) %></td>
  <td>
    <%= link_to 'Show',   test_question_path(@test) %>
    <%= link_to 'Edit',   edit_test_question_path(@test) %>
    <%= link_to 'Delete', test_question_path(@test),
                method: :delete,
                data: { confirm: 'Are you sure?'} %>
  </td>
</tr>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/edit.html.erb
<h1>Редактирование вопроса - <%= @question.title %></h1>

<%= form_for @question, url: { action: "update" } do |t| %>
  <%= t.label :title, 'Вопрос' %><br/>
  <%=	 t.text_field :title, size: 50 %><br/>
  <%= t.label :body, 'Описание вопроса' %><br/>
  <%=	 t.text_area :body, size: "60X12" %><br/>
  <%= t.label :published, 'Опубликован' %><br/>
  <%= t.check_box :published %>
  <br/><br/>
  <%= t.submit %>
<% end %>

app/views/questions/index.html.erb
<h1>Список вопросов для теста - <%= @test.title %></h1>
<% @questions.each do |question| %>
  <div><%= link_to question.title, [:edit, @test , question ] %></div>
<% end %>

app/views/questions/new.html.erb
<h1>Новый вопрос</h1>

<%= form_for @question, url: { action: "create" } do |t| %>
  <%= t.label :title, 'Вопрос' %><br/>
  <%=	 t.text_field :title, size: 50 %><br/>
  <%= t.label :body, 'Описание вопроса' %><br/>
  <%=	 t.text_area :body, size: "60X12" %><br/>
  <%= t.label :published, 'Опубликован' %><br/>
  <%= t.check_box :published %>
  <br/><br/>
  <%= t.submit %>
<% end %>

app/views/questions/show.html.erb
<h1>Просмотр вопроса</h1>
<p><%= @question.title %></p>
<p><%= @question.body %></p>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>